### PR TITLE
Add CI Testing

### PR DESCRIPTION
**Pull request by carpenterd777**
Adds a `yarn test` command using `jest-expo` and a Github workflow for CI.

### CODE REVIEW

**Comment by elenirotsides** [comment]
Should we bother doing any frontend tests? It might be hard to mock up the data to do so. I may have misunderstood last week when I asked this, but I thought we only decided to test in `peer-server`? @aej11a What do you think? I mean we _can_ write frontend tests, and I have experience in this area, but I'm thinking it might be tough to test via automation.

**Comment by carpenterd777** [comment]
I totally think that mocking location data is possible, and even if not - there will be some components that do not rely on location, and we can test those. I do not think we should forego tests on the front-end completely.

**Comment by elenirotsides** [comment]
Ah you're right about not all data being location dependent. We can totally test that situation. I guess we'll figure that out when we get to testing whatever UI we have. Overall, good stuff.

**Comment by aej11a** [comment]
While the PR looks good, personally I don't really see any value in this, like for example right now the snapshot file is literally a copy of the content from App's return, so currently no value, and it'll get harder to maintain snapshots as we add more components and views

**Comment by carpenterd777** [comment]
I can remove the snapshot test - we can keep frontend tests though just for testing the actual features.

**Comment by elenirotsides** [comment]
Yeah I think we can definitely do minimal frontend component testing. I don't think we'll be able to do anything more anyway, but it'll be good to make sure things are working as intended with CI testing. Worst case scenario, we'll just drop this lol so it won't hurt right now to attempt to write component tests.

**Review by elenirotsides — APPROVED** [review]

**Pull request merged**
