### PR TITLE
Fix filter box

### LINKED ISSUE #41: Filter box is not rendering correctly

### LINKED ISSUE #48: Fetch categories for filter box using Google's categories

### PR DESCRIPTION
**Pull request by dcarpenter31**
Fixes #41, Fixes #48

Fixes a bug where the filter box was not rendering anything. Also makes use of the Places API to get all of the actual categories that the API endpoint will end up returning. These have replaced the dummy categories. ~This list of categories is very long, so it was made into a `FlatList`, so that it could scroll and save memory.~ The package `react-native-select-multiple` was used, whose bread and butter component `SelectMultiple` is built using a `FlatList`. `FlatList`s save memory by not rendering the components that are not in the viewport. This package was selected in hope that it would be compatible with iOS. Finally, added some tests to help ensure that breaking changes to the box are not merged again.

### Known Issues

The `SelectMultiple` component uses the deprecated lifecycle function `componentWillReceiveProps`. Our options to remedy this are limited, since the component comes from an external package. We could rewrite the package for Peer using the latest React idioms, though this may take a while.

When scrolling through the list too fast, expo warns you that the list is slow to update. I have called `memo` on each filter list item to try and speed up the process, but it seems like more will need to be done before the list stops being slow to update. Solutions to this will need to be researched.

### CODE REVIEW

**Comment by carpenterd777** [comment]
@elenirotsides could you try running the command someone suggested in this [issue](https://github.com/react-native-checkbox/react-native-checkbox/issues/131)?
```
cd ios && pod install
```

**Comment by elenirotsides** [comment]
Yup, it looks like the same error https://github.com/Peer-Stevens/peer/pull/36#pullrequestreview-769794317

**Comment by carpenterd777** [comment]
> 
> 
> Yup, it looks like the same error [#36 (review)](https://github.com/Peer-Stevens/peer/pull/36#pullrequestreview-769794317)

were you able to overcome the error then?

**Comment by elenirotsides** [comment]
Unfortunately, I was not

**Comment by carpenterd777** [comment]
> The amount of items rendering in this list seems a bit overwhelming, I don't know if we want to limit these categories, but I think it's worth a discussion. Is there a way to broaden these categories, or is this all we can get from the API?

Yeah I agree - but I think that should be done in a separate PR, since we'll all have to decide on how to create broader categories

> Can we increase the font size of the list items? It seems a bit disproportional when compared with the other things on the screen, and also might benefit visually impaired folks better.

Yup, I can do that

> I did indeed notice the issue you mentioned in the description of this PR, I wonder what @aej11a 's thoughts are on this because I don't really know what the solution is if I'm being honest. According to this https://reactjs.org/blog/2018/03/27/update-on-async-rendering.html , it doesn't seem like this affects us majorly right now? We can probably just suppress the warning if we don't want to bother with this.

I'm not sure what can done about this other than rewriting the package ourselves or suppressing the warning like you said

> When the filters are expanded, the rest of the content on the page shifts in response to the list appearing, is there a way to fix this so it doesn't happen? Is this just an issue on iOS? See the video below:

This happens on Android too, and I think it is related to the styling on the places list, so I would need to take a look there first

**Comment by carpenterd777** [comment]
Current look on Android:

**Comment by carpenterd777** [comment]
@elenirotsides I'm not sure how I'm supposed to fix that - I don't have an iOS device to test a layout on. Also, we merged in #54 despite the app styling being wrong on Android

**Pull request merged**
