### PR TITLE
User can now unselect their selected filter

### LINKED ISSUE #187: Cannot unselect filter once it has been selected in the map screen
There is no way to return to the default state - no filters selected. After selecting a filter for the first time, the user must have on filter selected.

### PR DESCRIPTION
**Pull request by carpenterd777**
Users can still only select one filter, but now they can unselect the filter they have chosen to be returned to the filterless state. Also adds some tests.

Closes #187

### CODE REVIEW

**Comment by carpenterd777** [comment]
I simply cannot cover one line of this added change, please spare me 😭

**Comment by carpenterd777** [comment]
I uncovered a broken test while trying to fix the patch issue on this branch. I have no clue how to cover that line now - we'll probably have to merge this branch in by force.

**Comment by elenirotsides** [comment]
> I uncovered a broken test while trying to fix the patch issue on this branch. I have no clue how to cover that line now - we'll probably have to merge this branch in by force.

It looks like everything is fine now after merging main in; whatever changes you made in your other PRs that I have since merged into main must have resolved this issue @carpenterd777

**Review by elenirotsides — APPROVED** [review]
Everything works great!

**Pull request merged**
