### PR TITLE
Added Nearby Places List

### LINKED ISSUE #29: List view - places near you
Home screen:

- Map display is the top half of the screen
- List view is the bottom half of the screen with scrolling capabilities that list out the places near you with their respective accessibility rating per category
- Data will be mocked via a json file that we load into the component 

Optional for Demo 1:
- A user should be able to click on the place in list view to get more details (ie address, comments by other users, etc.)

### PR DESCRIPTION
**Pull request by jlora23**
I used a "dummy" image for now and was only able to get it to load using the method you can see in my code. In the future I would like to be able to display the specific places' image but for now it is just one 'static' image.
Closes #29

### CODE REVIEW

**Comment by carpenterd777** [comment]
If you forget the commands to merge in main, its:
```
git checkout main
git pull
git checkout list-view
git merge main
```

**Comment by elenirotsides** [comment]
You can't do an import of an image in typescript unless you define the type https://stackoverflow.com/questions/51100401/typescript-image-import @carpenterd777 I think we'll just go with this solution for now. In actuality, we'll be pulling this from an API, right? So this solution is only relevant for the application's current state

**Comment by carpenterd777** [comment]
Android version

**Comment by elenirotsides** [comment]
We can def merge this in and then fix that for Thursday

**Pull request merged**
